[project]
name = "roam-contextual-chatbot"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "dotenv>=0.9.9",
    "fastapi>=0.115.12",
    "gradio>=5.32.0",
    "openai>=1.82.1",
    "uvicorn>=0.34.3",
]
